version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-container
    ports:
      - "3001:3001"
    depends_on:
      - mysql
